"""GUI 多语言文本"""

TEXTS = {
    "zh": {
        "title": "Media Deduplicator v1.1",
        "start": "开始扫描去重",
        "pause": "暂停",
        "resume": "继续",
        "stop": "停止",
        "collect": "收集结果",
        "keep_best": "保留最高清晰度",
        "mark_copies": "自动识别副本批量标记删除",
        "import_kf": "导入关键帧缓存",
        "import_report": "导入报告",
        "select_folder": "选择文件夹:",
        "browse": "浏览...",
        "ready": "就绪",
        "open": "打开",
        "open_folder": "打开文件夹",
        "mark_delete": "标记删除",
        "restore": "恢复",
        "cancel_import": "取消导入",
        "lang_btn": "EN",
        "tip": "提示: 双击缩略图打开文件 | 右键路径可复制 | 点击'导入报告'直接加载之前的结果",

        "scanning": "正在扫描文件...",
        "processing_images": "正在处理图片哈希...",
        "extracting_keyframes": "正在提取视频关键帧...",
        "matching": "正在匹配重复视频...",
        "generating_report": "正在生成报告...",
        "paused": "已暂停",
        "paused_detail": "已暂停 — 可点击「收集结果」或「继续」",
        "stopped": "已停止",
        "stopped_detail": "扫描已被用户停止",
        "completed": "完成! 发现 {} 组重复文件",
        "all_done": "全部完成！ 发现 {} 组重复文件",
        "exported": "已导出报告至 results 目录",
        "init": "正在初始化去重器...",
        "start_scan": "启动扫描，请稍候...",
        "saving": "保存结果中...",
        "error": "错误: {}",
        "no_file": "扫描失败或没有文件",
        "invalid_folder": "错误: 请选择有效的文件夹",
        "pausing": "正在暂停...",
        "pausing_wait": "正在暂停，请等待当前任务结束...",
        "stopping": "正在停止...",
        "resuming": "继续运行...",
        "resuming_detail": "继续运行，从断点恢复...",

        "collecting": "正在收集当前发现的重复...",
        "collected": "已收集 {} 组重复",
        "paused_collected": "暂停 — 已发现 {} 组重复",
        "paused_stats": "暂停 — 已发现 {} 组重复 | 图片: {} | 视频: {}",

        "batch_done": "已标记删除 {} 个低清晰度文件",
        "batch_none": "没有可标记删除的文件",
        "copies_done": "已自动标记 {} 个副本文件",
        "copies_none": "没有找到可自动标记的副本文件",
        "batch_log": "[批量] 已标记删除 {} 个文件",

        "kf_loaded": "已加载 {} 个视频的关键帧缓存",
        "kf_log": "已加载关键帧缓存: {} 个视频（将在扫描时跳过未变化的文件）",
        "kf_cancelled": "已取消关键帧缓存",
        "kf_cancel_log": "已取消关键帧缓存，扫描时将重新提取所有视频",
        "import_fail": "导入失败",
        "kf_import_fail": "导入失败: {}",
        "import_success": "导入成功! 发现 {} 组重复文件",
        "import_report_done": "成功导入 {} 组重复文件",
        "import_error": "无法导入报告: {}",

        "mark_delete_fail": "标记删除失败",
        "restore_fail": "恢复失败",
        "restore_not_found": "找不到标记删除的文件",
        "restore_too_many": "冲突过多，请手动处理",
        "deleted_log": "[已标记删除] {}",
        "deleted_status": "已标记删除: {}",
        "restored_log": "[已恢复] {}",
        "restored_status": "已恢复: {}",
        "copied_path": "已复制路径: {}",
        "file_not_found": "文件不存在",
        "file_moved": "文件可能已被移动或删除: {}",
        "open_fail": "打开失败",
        "folder_open_fail": "无法打开文件夹: {}",
        "path_not_exist": "路径不存在",
        "both_missing": "文件及其所在目录均已不存在: {}",
        "file_open_fail": "无法打开文件: {}\n\n请检查是否有关联程序支持此文件类型",

        "tag_manual": "已标记删除",
        "tag_keep_best": "低清晰度 — 已标记",
        "tag_mark_copies": "副本 — 已标记",

        "found_log": "[读取失败] {} -- {}",
        "select_report": "选择之前的报告文件",
        "select_kf": "选择关键帧缓存文件",
        "confirm_delete_title": "确认删除",
        "confirm_delete_msg": "确定要删除吗？\n{}",

        "saved_folder": "已选择文件夹: {}",
        "folder_changed": "文件夹已变更，清空旧 checkpoint",
        "result_cleared": "结果已清空",

        "logs": "读取失败的文件（双击路径复制）",
        "duplicate_groups_list": "重复文件组列表 (点击查看)",
        "stat_format": "统计: {} 图片 | {} 视频 | {} 组重复 | 可节省 {:.2f} MB",
        "import_stat": "导入报告: {} 图片 | {} 视频 | {} 组重复 | 可节省 {:.2f} MB",

        # 列表项
        "file_type_image": "[图片]",
        "file_type_video": "[视频]",
        "files_unit": "个文件",

        # reason
        "reason_identical": "内容完全相同（指纹一致）",
        "reason_near_duplicate": "高度相似（可能是副本）",
        "reason_compressed": "压缩/重编码/不同分辨率",
        "reason_light_edit": "轻度剪辑",
        "reason_edited_compressed": "剪辑+压缩",
        "reason_cross_res": "跨分辨率压缩（关键帧偏移较大）",

        # 日志/统计标签
        "log_header": "日志",
        "progress_bar": "进度",
        "stats_bar": "统计",
        "failed_bar": "读取失败的文件（双击路径复制）",
        "list_bar": "重复文件组列表 (点击查看)",
        "eta_seconds": "剩余约 {}秒",
        "eta_minutes": "剩余约 {}分{:02d}秒",
    },
    "en": {
        "title": "Media Deduplicator v1.1",
        "start": "Start Scan",
        "pause": "Pause",
        "resume": "Resume",
        "stop": "Stop",
        "collect": "Collect Results",
        "keep_best": "Keep Best Quality",
        "mark_copies": "Auto Mark Duplicates",
        "import_kf": "Import Keyframe Cache",
        "import_report": "Import Report",
        "select_folder": "Select Folder:",
        "browse": "Browse...",
        "ready": "Ready",
        "open": "Open",
        "open_folder": "Open Folder",
        "mark_delete": "Mark Delete",
        "restore": "Restore",
        "cancel_import": "Cancel Import",
        "lang_btn": "中",
        "tip": "Tip: Double-click thumbnail to open | Right-click path to copy | Import Report to load results",

        "scanning": "Scanning files...",
        "processing_images": "Processing image hashes...",
        "extracting_keyframes": "Extracting video keyframes...",
        "matching": "Matching duplicate videos...",
        "generating_report": "Generating report...",
        "paused": "Paused",
        "paused_detail": "Paused — click Collect Results or Resume",
        "stopped": "Stopped",
        "stopped_detail": "Scan stopped by user",
        "completed": "Done! Found {} duplicate groups",
        "all_done": "All done! Found {} duplicate groups",
        "exported": "Report exported to results folder",
        "init": "Initializing...",
        "start_scan": "Starting scan, please wait...",
        "saving": "Saving results...",
        "error": "Error: {}",
        "no_file": "Scan failed or no files found",
        "invalid_folder": "Error: please select a valid folder",
        "pausing": "Pausing...",
        "pausing_wait": "Pausing, please wait for current task to finish...",
        "stopping": "Stopping...",
        "resuming": "Resuming...",
        "resuming_detail": "Resuming from checkpoint...",

        "collecting": "Collecting discovered duplicates...",
        "collected": "Collected {} duplicate groups",
        "paused_collected": "Paused — found {} duplicate groups",
        "paused_stats": "Paused — {} groups | Images: {} | Videos: {}",

        "batch_done": "Marked {} low-quality files for deletion",
        "batch_none": "No files to mark",
        "copies_done": "Auto-marked {} duplicate files",
        "copies_none": "No copies found to auto-mark",
        "batch_log": "[Batch] Marked {} files for deletion",

        "kf_loaded": "Loaded {} video keyframe caches",
        "kf_log": "Keyframe cache loaded: {} videos (unchanged files will be skipped)",
        "kf_cancelled": "Keyframe cache cancelled",
        "kf_cancel_log": "Keyframe cache cancelled, all videos will be re-extracted",
        "import_fail": "Import Failed",
        "kf_import_fail": "Import failed: {}",
        "import_success": "Import successful! Found {} duplicate groups",
        "import_report_done": "Successfully imported {} duplicate groups",
        "import_error": "Failed to import report: {}",

        "mark_delete_fail": "Mark Delete Failed",
        "restore_fail": "Restore Failed",
        "restore_not_found": "Marked file not found",
        "restore_too_many": "Too many conflicts, please handle manually",
        "deleted_log": "[Marked] {}",
        "deleted_status": "Marked for deletion: {}",
        "restored_log": "[Restored] {}",
        "restored_status": "Restored: {}",
        "copied_path": "Path copied: {}",
        "file_not_found": "File Not Found",
        "file_moved": "File may have been moved or deleted: {}",
        "open_fail": "Open Failed",
        "folder_open_fail": "Cannot open folder: {}",
        "path_not_exist": "Path Not Found",
        "both_missing": "File and its directory no longer exist: {}",
        "file_open_fail": "Cannot open file: {}\n\nPlease check if an associated program supports this file type",

        "tag_manual": "Marked for Deletion",
        "tag_keep_best": "Low Quality — Marked",
        "tag_mark_copies": "Copy — Marked",

        "found_log": "[Read Failed] {} -- {}",
        "select_report": "Select report file",
        "select_kf": "Select keyframe cache file",
        "confirm_delete_title": "Confirm Delete",
        "confirm_delete_msg": "Are you sure you want to delete?\n{}",

        "saved_folder": "Folder selected: {}",
        "folder_changed": "Folder changed, clearing old checkpoint",
        "result_cleared": "Results cleared",

        "logs": "Failed files (double-click to copy path)",
        "duplicate_groups_list": "Duplicate Groups (click to view)",
        "stat_format": "Stats: {} images | {} videos | {} groups | can save {:.2f} MB",
        "import_stat": "Import: {} images | {} videos | {} groups | can save {:.2f} MB",

        "file_type_image": "[Image]",
        "file_type_video": "[Video]",
        "files_unit": " files",

        "reason_identical": "Identical",
        "reason_near_duplicate": "Near Duplicate",
        "reason_compressed": "Compressed / Re-encoded",
        "reason_light_edit": "Light Edit",
        "reason_edited_compressed": "Edited + Compressed",
        "reason_cross_res": "Cross-Resolution (keyframe offset)",

        "log_header": "Log",
        "progress_bar": "Progress",
        "stats_bar": "Stats",
        "failed_bar": "Failed files (double-click to copy)",
        "list_bar": "Duplicate Groups (click to view)",
        "eta_seconds": "~{}s remaining",
        "eta_minutes": "~{}min{:02d}s remaining",
    },
}


def get_text(lang, key, *args):
    """获取翻译文本，支持 format 参数"""
    text = TEXTS.get(lang, TEXTS["en"]).get(key, key)
    if args:
        text = text.format(*args)
    return text
